theme: jekyll-theme-minimal
title: Edmond W. W. Chan
description: PhD (Internet Performance & Security)<br />edmond at edmond.one<br /><a target="_blank" rel="noreferrer noopener" href="https://linkedin.com/in/edmondwwchan">LinkedIn</a>
logo: images/edmond.jpg
google_analytics_gtag: G-JJ9VEJYERP
#google_analytics: UA-172859482-1
