theme: jekyll-theme-minimal
title: Edmond W. W. Chan
description: PhD, CISSP<br />edmond0chan at gmail.com<br /><a href="https://github.com/edmondwwchan">@edmondwwchan</a>
logo: images/edmond.jpg
google_analytics: UA-172859482-1