theme: jekyll-theme-minimal
title: Edmond W. W. Chan
description: PhD, CISSP<br />edmond at edmond.one<br /><a href="https://github.com/edmondwwchan">@edmondwwchan</a><a href="https://linkedin.com/in/edmondwwchan">LinkedIn Profile</a>
logo: images/edmond.jpg
google_analytics: UA-172859482-1
